# Generated by Django 4.1 on 2023-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.URLField(null=True)),
                ('singer', models.CharField(max_length=200, null=True)),
                ('categories', models.CharField(help_text='بر اساس | باید جدا شوند', max_length=300, null=True)),
                ('link_128', models.URLField(null=True)),
                ('link_320', models.URLField(null=True)),
                ('url_page', models.URLField()),
                ('is_out', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
