# Generated by Django 4.1 on 2023-07-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='categories',
            field=models.CharField(blank=True, help_text='بر اساس | باید جدا شوند', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='link_128',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='link_320',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
