# Generated by Django 4.1 on 2023-07-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='get_category_by',
            field=models.TextField(help_text='گرفتن دسته بندی بر اساس', null=True),
        ),
    ]
